#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Tk-MARC
version:      1.3
version_from: lib/Tk/MARC.pm
installdirs:  site
requires:
    MARC::Descriptions:            0
    MARC::Record:                  1.34
    Test::More:                    0
    Tk:                            0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.13
